spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:1999/chat_db
    username: 'postgres'
    password: 'postgres'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          #         https
          issuer-uri: https://localhost:1234/auth/realms/go-selling-api
          jwk-set-uri: https://localhost:1234/auth/realms/go-selling-api/protocol/openid-connect/certs
#          local
#          issuer-uri: http://localhost:1234/auth/realms/go-selling-api
#          jwk-set-uri: http://localhost:1234/auth/realms/go-selling-api/protocol/openid-connect/certs
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka
openapi:
  service:
    title: chat-service
    version: 1.0.0
    url: http://localhost:8080

springdoc:
  api-docs:
    path: /chat-service/v3/api-docs
  swagger-ui:
    path: /chat-service/swagger-ui.html
